import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createCanvas } from 'pmx-canvas';
import {
  contextCards,
  ledgerSummary,
  ownershipLoad,
  stageDefectCounts,
  traceEvents,
  weeklyMetrics,
} from './data';
import {
  buildControlTowerSpec,
  buildEmbeddedChartsSpec,
  buildPricingTableSpec,
  buildReleaseIntakeSpec,
  buildServiceMatrixSpec,
  buildSettingsFormSpec,
  buildUserProfileCardSpec,
} from './json-render-specs';

function getNumberFlag(args: string[], name: string, fallback: number): number {
  const flag = args.find((entry) => entry.startsWith(`${name}=`));
  if (!flag) return fallback;
  const parsed = Number(flag.slice(name.length + 1));
  return Number.isFinite(parsed) ? parsed : fallback;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolvePromise) => setTimeout(resolvePromise, ms));
}

async function assertHtmlContains(url: string, expected: string): Promise<void> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`GET ${url} failed with ${response.status}`);
  }
  const html = await response.text();
  if (!html.includes(expected)) {
    throw new Error(`Expected ${url} to include "${expected}"`);
  }
}

async function postJson(url: string, body: unknown): Promise<unknown> {
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  if (!response.ok) {
    throw new Error(`POST ${url} failed with ${response.status}`);
  }
  return response.json();
}

const args = process.argv.slice(2);
const port = getNumberFlag(args, '--port', 4513);
const hold = args.includes('--hold');
const demoRoot = dirname(fileURLToPath(import.meta.url));
const baseUrl = `http://127.0.0.1:${port}`;

const articlePath = join(demoRoot, 'article.md');
const imagePath = join(demoRoot, 'pipeline-overview.svg');
const dataPath = join(demoRoot, 'data.ts');
const articleFile = readFileSync(articlePath, 'utf-8');
const webAppPath = join(demoRoot, 'web', 'App.tsx');
const webCssPath = join(demoRoot, 'web', 'index.css');
const webDataPath = join(demoRoot, 'data.ts');
const artifactApp = readFileSync(webAppPath, 'utf-8');
const artifactCss = readFileSync(webCssPath, 'utf-8');
const artifactData = readFileSync(webDataPath, 'utf-8');

const canvas = createCanvas({ port });

let stopped = false;
const stopCanvas = (): void => {
  if (stopped) return;
  stopped = true;
  canvas.stop();
};

process.on('SIGINT', () => {
  stopCanvas();
  process.exit(0);
});

process.on('SIGTERM', () => {
  stopCanvas();
  process.exit(0);
});

await canvas.start({ open: false });
canvas.clear();

const articleId = canvas.addNode({
  type: 'markdown',
  title: 'Synthetic SDLC Report',
  content: articleFile,
  x: 40,
  y: 40,
  width: 760,
  height: 760,
});

const imageId = canvas.addNode({
  type: 'image',
  title: 'Pipeline Atlas',
  content: imagePath,
  x: 40,
  y: 840,
  width: 760,
  height: 320,
});

const articleFileId = canvas.addNode({
  type: 'file',
  title: 'Article Markdown',
  content: articlePath,
  x: 40,
  y: 1190,
  width: 760,
  height: 360,
});

const appFileId = canvas.addNode({
  type: 'file',
  title: 'Artifact App',
  content: webAppPath,
  x: 40,
  y: 1580,
  width: 760,
  height: 360,
});

const dataFileId = canvas.addNode({
  type: 'file',
  title: 'Synthetic Data Model',
  content: dataPath,
  x: 40,
  y: 1970,
  width: 760,
  height: 360,
});

const statusId = canvas.addNode({
  type: 'status',
  title: 'Release Train Status',
  x: 840,
  y: 40,
  width: 340,
  height: 170,
});

const statusNode = canvas.getNode(statusId);
canvas.updateNode(statusId, {
  data: {
    ...(statusNode?.data ?? {}),
    title: 'Release Train Status',
    phase: 'active',
    detail: 'weekly train / synthetic telemetry',
    message: 'Integration tests are the current bottleneck. Build and rollback posture remain healthy.',
    level: 'warn',
    activeTool: 'pipeline.evaluate',
    subagent: {
      state: 'running',
      name: 'published-consumer-check',
    },
  },
});

const contextId = canvas.addNode({
  type: 'context',
  title: 'Pinned Briefing',
  x: 1220,
  y: 40,
  width: 360,
  height: 320,
});

const contextNode = canvas.getNode(contextId);
canvas.updateNode(contextId, {
  data: {
    ...(contextNode?.data ?? {}),
    title: 'Pinned Briefing',
    cards: contextCards,
    currentTokens: 18320,
    tokenLimit: 32000,
    utilization: 0.57,
    messagesLength: 14,
    auxTabs: [
      {
        id: 'release-guide',
        url: `${baseUrl}/artifact?path=artifacts/sdlc-control-room.html`,
        reason: 'Artifact route generated by the packaged install',
      },
    ],
  },
});

const ledgerId = canvas.addNode({
  type: 'ledger',
  title: 'Synthetic Execution Ledger',
  x: 1220,
  y: 390,
  width: 360,
  height: 240,
});

const ledgerNode = canvas.getNode(ledgerId);
canvas.updateNode(ledgerId, {
  data: {
    ...(ledgerNode?.data ?? {}),
    title: 'Synthetic Execution Ledger',
    ...ledgerSummary,
  },
});

const traceIds = traceEvents.map((trace, index) => {
  const id = canvas.addNode({
    type: 'trace',
    title: trace.title,
    x: 840,
    y: 240 + index * 76,
    width: 340,
    height: 60,
  });
  const node = canvas.getNode(id);
  canvas.updateNode(id, {
    data: {
      ...(node?.data ?? {}),
      title: trace.title,
      toolName: trace.toolName,
      category: trace.category,
      status: trace.status,
      duration: trace.duration,
      resultSummary: trace.resultSummary,
    },
  });
  return id;
});

const artifactBuild = await canvas.buildWebArtifact({
  title: 'SDLC Control Room Artifact',
  appTsx: artifactApp,
  indexCss: artifactCss,
  files: {
    'src/data.ts': artifactData,
  },
  projectPath: 'artifacts/.web-artifacts/sdlc-control-room',
  outputPath: 'artifacts/sdlc-control-room.html',
  openInCanvas: true,
});

if (!artifactBuild.nodeId || !artifactBuild.url) {
  throw new Error('Artifact node was not opened on the canvas.');
}

const artifactNode = canvas.getNode(artifactBuild.nodeId);
canvas.updateNode(artifactBuild.nodeId, {
  position: { x: 840, y: 780 },
  size: { width: 980, height: 690 },
  data: {
    ...(artifactNode?.data ?? {}),
    title: 'SDLC Control Room Artifact',
  },
});

const dashboard = canvas.addJsonRenderNode({
  title: 'Control Tower Widgets',
  spec: buildControlTowerSpec(),
  x: 840,
  y: 1500,
  width: 520,
  height: 640,
});

const intake = canvas.addJsonRenderNode({
  title: 'Release Gate Intake',
  spec: buildReleaseIntakeSpec(),
  x: 1390,
  y: 1500,
  width: 520,
  height: 720,
});

const matrix = canvas.addJsonRenderNode({
  title: 'Service Readiness Matrix',
  spec: buildServiceMatrixSpec(),
  x: 840,
  y: 2250,
  width: 1070,
  height: 360,
});

const profileCard = canvas.addJsonRenderNode({
  title: 'User Profile Card',
  spec: buildUserProfileCardSpec(),
  x: 840,
  y: 2650,
  width: 500,
  height: 420,
});

const settingsForm = canvas.addJsonRenderNode({
  title: 'Account Settings',
  spec: buildSettingsFormSpec(),
  x: 1370,
  y: 2650,
  width: 540,
  height: 500,
});

const pricingTable = canvas.addJsonRenderNode({
  title: 'Pricing Table',
  spec: buildPricingTableSpec(),
  x: 840,
  y: 3180,
  width: 1070,
  height: 560,
});

const embeddedCharts = canvas.addJsonRenderNode({
  title: 'Embedded Charts Dashboard',
  spec: buildEmbeddedChartsSpec(),
  x: 840,
  y: 3770,
  width: 1070,
  height: 980,
});

const leadTimeGraph = canvas.addGraphNode({
  title: 'Lead Time Trend',
  graphType: 'line',
  data: weeklyMetrics.map((entry) => ({
    label: entry.week,
    value: entry.leadTimeHours,
  })),
  xKey: 'label',
  yKey: 'value',
  color: '#e9c46a',
  x: 1830,
  y: 780,
  width: 540,
  heightPx: 420,
});

const defectGraph = canvas.addGraphNode({
  title: 'Defects by Stage',
  graphType: 'bar',
  data: stageDefectCounts.map((entry) => ({
    label: entry.stage,
    value: entry.defects,
  })),
  xKey: 'label',
  yKey: 'value',
  color: '#e76f51',
  x: 1830,
  y: 1220,
  width: 540,
  heightPx: 420,
});

const ownershipGraph = canvas.addGraphNode({
  title: 'Operational Load',
  graphType: 'pie',
  data: ownershipLoad,
  nameKey: 'name',
  valueKey: 'value',
  x: 1830,
  y: 1660,
  width: 540,
  heightPx: 420,
});

canvas.addEdge({
  from: articleId,
  to: artifactBuild.nodeId,
  type: 'references',
  label: 'narrates',
});

canvas.addEdge({
  from: artifactBuild.nodeId,
  to: dashboard.id,
  type: 'flow',
  label: 'summarized as',
});

canvas.addEdge({
  from: dashboard.id,
  to: intake.id,
  type: 'depends-on',
  label: 'operator inputs',
});

canvas.addEdge({
  from: intake.id,
  to: matrix.id,
  type: 'relation',
  label: 'updates readiness',
});

canvas.addEdge({
  from: matrix.id,
  to: profileCard.id,
  type: 'flow',
  label: 'persona reference',
});

canvas.addEdge({
  from: profileCard.id,
  to: settingsForm.id,
  type: 'depends-on',
  label: 'preference editing',
});

canvas.addEdge({
  from: settingsForm.id,
  to: pricingTable.id,
  type: 'flow',
  label: 'plan selection',
});

canvas.addEdge({
  from: pricingTable.id,
  to: embeddedCharts.id,
  type: 'references',
  label: 'usage analytics',
});

canvas.addEdge({
  from: statusId,
  to: leadTimeGraph.id,
  type: 'flow',
  label: 'tracked by',
  animated: true,
});

canvas.addEdge({
  from: statusId,
  to: defectGraph.id,
  type: 'flow',
  label: 'pressure',
});

canvas.addEdge({
  from: ledgerId,
  to: ownershipGraph.id,
  type: 'references',
  label: 'allocation',
});

canvas.addEdge({
  from: contextId,
  to: dashboard.id,
  type: 'depends-on',
  label: 'pinned context',
});

canvas.addEdge({
  from: articleFileId,
  to: appFileId,
  type: 'references',
  label: 'example source',
});

traceIds.reduce((previousId, currentId) => {
  if (previousId) {
    canvas.addEdge({
      from: previousId,
      to: currentId,
      type: 'flow',
      label: 'then',
      animated: true,
    });
  }
  return currentId;
}, '');

canvas.createGroup({
  title: 'Narrative & Evidence',
  childIds: [articleId, imageId, articleFileId, appFileId, dataFileId],
  color: '#e76f51',
});

canvas.createGroup({
  title: 'Operational Telemetry',
  childIds: [statusId, contextId, ledgerId, ...traceIds],
  color: '#2a9d8f',
});

canvas.createGroup({
  title: 'Structured UI Surfaces',
  childIds: [
    artifactBuild.nodeId,
    dashboard.id,
    intake.id,
    matrix.id,
    profileCard.id,
    settingsForm.id,
    pricingTable.id,
    embeddedCharts.id,
    leadTimeGraph.id,
    defectGraph.id,
    ownershipGraph.id,
  ],
  color: '#e9c46a',
});

await postJson(`${baseUrl}/api/canvas/context-pins`, {
  nodeIds: [articleId, artifactBuild.nodeId, dashboard.id],
});

await postJson(`${baseUrl}/api/canvas/snapshots`, {
  name: 'published-consumer-baseline',
});

await sleep(500);

await assertHtmlContains(`${baseUrl}${artifactBuild.url}`, 'Delivery Control Room');
await assertHtmlContains(`${baseUrl}${dashboard.url}`, 'Control Tower Widgets');
await assertHtmlContains(`${baseUrl}${profileCard.url}`, 'User Profile');
await assertHtmlContains(`${baseUrl}${settingsForm.url}`, 'Account Settings');
await assertHtmlContains(`${baseUrl}${pricingTable.url}`, 'Simple, transparent pricing');
await assertHtmlContains(`${baseUrl}${embeddedCharts.url}`, 'Embedded Charts Dashboard');
await assertHtmlContains(`${baseUrl}${embeddedCharts.url}`, 'LineChart');
await assertHtmlContains(`${baseUrl}${embeddedCharts.url}`, 'BarChart');
await assertHtmlContains(`${baseUrl}${embeddedCharts.url}`, 'PieChart');
await assertHtmlContains(`${baseUrl}${leadTimeGraph.url}`, 'LineChart');
await assertHtmlContains(`${baseUrl}${defectGraph.url}`, 'BarChart');
await assertHtmlContains(`${baseUrl}${ownershipGraph.url}`, 'PieChart');

const stateResponse = await fetch(`${baseUrl}/api/canvas/state`);
if (!stateResponse.ok) {
  throw new Error(`Canvas state endpoint failed with ${stateResponse.status}`);
}
const state = (await stateResponse.json()) as {
  nodes: Array<{ id: string; type: string }>;
  edges: Array<{ id: string }>;
};

if (state.nodes.length < 22) {
  throw new Error(`Expected at least 22 nodes, found ${state.nodes.length}`);
}

const pinsResponse = await fetch(`${baseUrl}/api/canvas/pinned-context`);
if (!pinsResponse.ok) {
  throw new Error(`Pinned context endpoint failed with ${pinsResponse.status}`);
}
const pins = (await pinsResponse.json()) as { count: number };
if (pins.count !== 3) {
  throw new Error(`Expected 3 pinned nodes, found ${pins.count}`);
}

const snapshotsResponse = await fetch(`${baseUrl}/api/canvas/snapshots`);
if (!snapshotsResponse.ok) {
  throw new Error(`Snapshot list failed with ${snapshotsResponse.status}`);
}
const snapshots = (await snapshotsResponse.json()) as Array<{ name: string }>;
if (!snapshots.some((snapshot) => snapshot.name === 'published-consumer-baseline')) {
  throw new Error('Expected published-consumer-baseline snapshot to exist');
}

console.log(
  JSON.stringify(
    {
      url: `${baseUrl}/workbench`,
      nodeCount: state.nodes.length,
      edgeCount: state.edges.length,
      artifactPath: artifactBuild.filePath,
      projectPath: artifactBuild.projectPath,
      pins: pins.count,
    },
    null,
    2,
  ),
);

if (hold) {
  console.log(`Published consumer demo ready at ${baseUrl}/workbench`);
  setInterval(() => {}, 60_000);
  await new Promise(() => {});
}

stopCanvas();
