import { afterEach, beforeEach, describe, expect, test } from 'bun:test';
import { canvasState, type CanvasNodeState } from '../../src/server/canvas-state.ts';
import { describeCanvasSchema } from '../../src/server/canvas-schema.ts';
import { seedDemoCanvas } from '../../src/server/demo.ts';
import { buildHtmlPrimitive, HTML_PRIMITIVE_KINDS, isHtmlPrimitiveKind } from '../../src/server/html-primitives.ts';
import { NODE_TYPES } from '../../src/server/operations/ops/nodes.ts';
import { readAxFlow, readAxStep } from '../../src/shared/ax-flow.ts';
import { createTestWorkspace, removeTestWorkspace, resetCanvasForTests } from './helpers.ts';

/**
 * The demo board is generated by `scripts/generate-demo-board.ts` — never hand
 * edited. These assertions are the contract that script has to keep: full
 * surface coverage (every public node type, graph type and HTML primitive), a
 * layout that does not collide, and a board that renders with nothing but the
 * fixture (no disk, no network, no live app session).
 *
 * Node IDs are stable `demo-*` keys assigned at export time, but this file
 * deliberately keys off types and roles rather than individual ids so the board
 * can be re-laid-out without touching the test.
 */

/** The 15 public node types: everything node.add accepts, plus the two structured-viewer routes. */
const PUBLIC_NODE_TYPES = new Set<string>([...NODE_TYPES, 'json-render', 'graph']);
const GRAPH_TYPES = describeCanvasSchema().graph.graphTypes;
const EDGE_TYPES = ['flow', 'depends-on', 'relation', 'references'];

describe('demo canvas seed', () => {
  let workspaceRoot = '';

  beforeEach(() => {
    workspaceRoot = createTestWorkspace('pmx-canvas-demo-');
    resetCanvasForTests(workspaceRoot);
  });

  afterEach(() => {
    removeTestWorkspace(workspaceRoot);
  });

  test('seeds the showcase board with the expected counts', () => {
    expect(seedDemoCanvas()).toEqual({ nodes: 69, edges: 9, groups: 1 });
    const layout = canvasState.getLayout();
    expect(layout.nodes).toHaveLength(69);
    expect(layout.edges).toHaveLength(9);
    expect(layout.annotations).toHaveLength(1);
  });

  test('covers every public node type and no internal ones', () => {
    seedDemoCanvas();
    const types = new Set<string>(canvasState.getLayout().nodes.map((node) => node.type));

    for (const type of PUBLIC_NODE_TYPES) {
      expect(types.has(type), `demo board is missing a "${type}" node`).toBe(true);
    }
    expect([...types].filter((type) => !PUBLIC_NODE_TYPES.has(type))).toEqual([]);
    expect(types.has('prompt')).toBe(false);
    expect(types.has('response')).toBe(false);
  });

  test('shows every canonical and Tufte graph type exactly once', () => {
    seedDemoCanvas();
    const graphTypes = canvasState
      .getLayout()
      .nodes.filter((node) => node.type === 'graph')
      .map((node) => (node.data.graphConfig as { graphType?: string } | undefined)?.graphType);

    expect([...graphTypes].sort()).toEqual([...GRAPH_TYPES].sort());
    // Tufte primitives specifically — the compact bottom row of the charts band.
    for (const tufte of ['sparkline', 'dot-plot', 'bullet', 'slopegraph']) {
      expect(graphTypes, `demo board is missing the ${tufte} chart`).toContain(tufte);
    }
  });

  test('shows every HTML primitive kind', () => {
    seedDemoCanvas();
    const kinds = canvasState
      .getLayout()
      .nodes.map((node) => node.data.htmlPrimitive)
      .filter((kind): kind is string => typeof kind === 'string');

    expect([...kinds].sort()).toEqual([...HTML_PRIMITIVE_KINDS].sort());
    // Each primitive carries its generated surface, not just its input data.
    for (const node of canvasState.getLayout().nodes) {
      if (typeof node.data.htmlPrimitive !== 'string') continue;
      expect(typeof node.data.html, `${node.data.htmlPrimitive} has no generated HTML`).toBe('string');
      expect((node.data.html as string).length).toBeGreaterThan(500);
    }
  });

  test('every stored primitive surface still matches what its renderer produces', () => {
    // The fixture embeds each primitive's GENERATED html. Editing a renderer
    // without re-running the generator leaves the board shipping stale markup —
    // and it fails silently: every other assertion here checks counts and
    // coverage, which a month-old surface satisfies just as well as a current
    // one. That already happened once: the board shipped a layout bug that had
    // been fixed in the renderer minutes earlier, and nothing went red.
    //
    // Rebuilding from `data.primitiveData` (the generator's INPUT — not
    // `data.data`) reproduces the surface byte-for-byte, so any drift here means
    // the fixture is stale: re-run `bun run scripts/generate-demo-board.ts`
    // AFTER the last renderer edit.
    seedDemoCanvas();
    const stale: string[] = [];
    for (const node of canvasState.getLayout().nodes) {
      const kind = node.data.htmlPrimitive;
      if (typeof kind !== 'string' || !isHtmlPrimitiveKind(kind)) continue;
      const rebuilt = buildHtmlPrimitive({
        kind,
        title: typeof node.data.title === 'string' ? node.data.title : undefined,
        data: (node.data.primitiveData ?? {}) as Record<string, unknown>,
      });
      if (rebuilt.html !== node.data.html) {
        stale.push(`${kind} (stored ${String(node.data.html).length}B, renderer ${rebuilt.html.length}B)`);
      }
    }
    expect(stale, `stale primitive surfaces — regenerate the demo fixture: ${stale.join(', ')}`).toEqual([]);
  });

  test('uses one group as an example, not as the board structure', () => {
    seedDemoCanvas();
    const layout = canvasState.getLayout();
    const groups = layout.nodes.filter((node) => node.type === 'group');
    expect(groups).toHaveLength(1);

    for (const group of groups) {
      const children = group.data.children;
      expect(Array.isArray(children), `${group.id} stores children`).toBe(true);
      expect((children as string[]).length).toBeGreaterThanOrEqual(2);
      for (const childId of children as string[]) {
        const child = layout.nodes.find((node) => node.id === childId);
        expect(child, `${group.id} has missing child ${childId}`).toBeDefined();
        expect(child?.data.parentGroup).toBe(group.id);
        expect(child!.position.x).toBeGreaterThanOrEqual(group.position.x + 40);
        expect(child!.position.y).toBeGreaterThanOrEqual(group.position.y + 40);
        expect(child!.position.x + child!.size.width).toBeLessThanOrEqual(group.position.x + group.size.width - 40);
        expect(child!.position.y + child!.size.height).toBeLessThanOrEqual(group.position.y + group.size.height - 40);
      }
    }
  });

  test('connects nearby nodes with all four edge types', () => {
    seedDemoCanvas();
    const layout = canvasState.getLayout();
    const nodesById = new Map(layout.nodes.map((node) => [node.id, node]));

    for (const type of EDGE_TYPES) {
      expect(
        layout.edges.some((edge) => edge.type === type),
        `demo board is missing a "${type}" edge`,
      ).toBe(true);
    }
    expect(layout.edges.some((edge) => edge.animated === true)).toBe(true);
    expect(layout.edges.some((edge) => edge.style === 'dashed')).toBe(true);
    expect(layout.edges.some((edge) => typeof edge.label === 'string' && edge.label.length > 0)).toBe(true);

    for (const edge of layout.edges) {
      const from = nodesById.get(edge.from);
      const to = nodesById.get(edge.to);
      expect(from, `${edge.id} has missing source ${edge.from}`).toBeDefined();
      expect(to, `${edge.id} has missing target ${edge.to}`).toBeDefined();
      const distance = Math.hypot(
        from!.position.x + from!.size.width / 2 - (to!.position.x + to!.size.width / 2),
        from!.position.y + from!.size.height / 2 - (to!.position.y + to!.size.height / 2),
      );
      expect(distance, `${edge.id} is too long for the demo layout`).toBeLessThan(2200);
    }
  });

  test('pins resolve to nodes on the board', () => {
    seedDemoCanvas();
    const pins = Array.from(canvasState.contextPinnedNodeIds);
    const nodeIds = new Set(canvasState.getLayout().nodes.map((node) => node.id));

    expect(pins.length).toBeGreaterThanOrEqual(2);
    for (const pin of pins) {
      expect(nodeIds.has(pin), `pinned node ${pin} is not on the board`).toBe(true);
    }
  });

  test('restores the ⑧ agent-at-work flow with working controls', () => {
    // The point of this band is that its Start/Done buttons actually run. They
    // emit `ax.work.update` for `data.axStep.workItemId`, so a fixture that
    // restored the step NODES but not their WORK ITEMS would render a board that
    // looks live and 404s the moment anyone presses a control.
    seedDemoCanvas();
    const layout = canvasState.getLayout();
    const workItemIds = new Set(canvasState.getWorkItems().map((item) => item.id));

    const steps = layout.nodes.filter((node) => readAxStep(node.data) !== null);
    expect(steps).toHaveLength(4);
    for (const node of layout.nodes) {
      const step = readAxStep(node.data);
      if (!step) continue;
      expect(workItemIds.has(step.workItemId), `${node.id} points at missing work item ${step.workItemId}`).toBe(true);
    }
    // …and the reverse: every restored work item still anchors to a real node.
    const nodeIds = new Set(layout.nodes.map((node) => node.id));
    for (const item of canvasState.getWorkItems()) {
      expect(item.nodeIds.length, `work item ${item.id} lost its node anchor`).toBeGreaterThan(0);
      for (const id of item.nodeIds)
        expect(nodeIds.has(id), `work item ${item.id} references missing ${id}`).toBe(true);
    }

    // The anchor step carries the whole flow, so its native loop controls render.
    const anchors = layout.nodes.filter((node) => readAxFlow(node.data) !== null);
    expect(anchors).toHaveLength(1);
    const flow = readAxFlow(anchors[0].data);
    expect(flow?.steps.map((step) => step.nodeId)).toEqual(steps.map((node) => node.id));

    // Mid-task, not a fresh queue: mixed statuses on both the work items and the
    // `axWorkStatus` chips mirrored onto the nodes.
    const byIndex = [...steps].sort((a, b) => readAxStep(a.data)!.index - readAxStep(b.data)!.index);
    expect(byIndex.map((node) => node.data.axWorkStatus)).toEqual(['done', 'in-progress', 'todo', 'todo']);
    const statusOf = (node: CanvasNodeState): string =>
      canvasState.getWorkItems().find((item) => item.id === readAxStep(node.data)!.workItemId)!.status;
    expect(byIndex.map(statusOf)).toEqual(['done', 'in-progress', 'todo', 'todo']);

    // The step the agent is on is the human's pin — that is the whole point.
    const active = byIndex[1];
    expect(Array.from(canvasState.contextPinnedNodeIds)).toContain(active.id);
  });

  test('lays out every node without overlaps', () => {
    seedDemoCanvas();
    // Group frames legitimately contain their own children.
    const nodes = canvasState.getLayout().nodes.filter((node) => node.type !== 'group');

    for (let i = 0; i < nodes.length; i += 1) {
      for (let j = i + 1; j < nodes.length; j += 1) {
        const a = nodes[i];
        const b = nodes[j];
        const separated =
          a.position.x + a.size.width <= b.position.x ||
          b.position.x + b.size.width <= a.position.x ||
          a.position.y + a.size.height <= b.position.y ||
          b.position.y + b.size.height <= a.position.y;
        expect(separated, `${a.id} overlaps ${b.id}`).toBe(true);
      }
    }
  });

  test('renders offline — no workspace paths, live sessions, or fetch-on-render', () => {
    seedDemoCanvas();
    const nodes = canvasState.getLayout().nodes;
    const byType = (type: string): CanvasNodeState[] => nodes.filter((node) => node.type === type);

    // File nodes are inline: the cached text renders without ever reading disk.
    for (const node of byType('file')) {
      expect(typeof node.data.fileContent, `${node.id} has no inline content`).toBe('string');
      expect((node.data.fileContent as string).length).toBeGreaterThan(0);
    }
    // One of them is a .csv so the delimited-table rendering is on show.
    expect(byType('file').some((node) => String(node.data.path ?? '').endsWith('.csv'))).toBe(true);

    // Images are inline data URIs, never file paths or remote URLs.
    for (const node of byType('image')) {
      expect(String(node.data.src)).toStartWith('data:image/');
    }

    // Webpage nodes render from their cached snapshot.
    for (const node of byType('webpage')) {
      expect(node.data.status).toBe('ready');
      expect(String(node.data.excerpt).length).toBeGreaterThan(0);
      expect(node.data.error).toBeUndefined();
    }

    // MCP app nodes carry their own document and never wait on a live session.
    for (const node of byType('mcp-app')) {
      expect(node.data.mode).toBe('ext-app');
      expect(typeof node.data.html).toBe('string');
      expect(node.data.sessionStatus).toBeUndefined();
      expect(node.data.appSessionId).toBeUndefined();
    }

    // Every non-group node keeps the frame the generator laid out, so the
    // browser's auto-fit cannot reflow the board on first open.
    for (const node of nodes) {
      if (node.type === 'group') continue;
      expect(node.data.strictSize, `${node.id} is missing strictSize`).toBe(true);
    }

    // Nothing on the board is a web artifact (those need a built bundle on disk).
    expect(nodes.some((node) => node.data.viewerType === 'web-artifact')).toBe(false);
    expect(nodes.some((node) => node.data.kind === 'web-artifact')).toBe(false);
  });
});
